#!/usr/bin/env bash
# Init script to start/stop/restart manage_my_process

PID_FILE="/tmp/my_process.pid"

start() {
    ./manage_my_process &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
}

stop() {
    kill "$(cat $PID_FILE)"
    rm -f "$PID_FILE"
    echo "manage_my_process stopped"
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
