#!/usr/bin/env bash
# Script that handles signals and writes PID file

echo $$ > /tmp/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -f /tmp/myscript.pid; exit' SIGTERM
trap 'rm -f /tmp/myscript.pid; exit' SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
